# encoding: utf-8

# Concept categories
ConceptCategory.delete_all
ConceptCategory.create(label: "Services")
ConceptCategory.create(label: "Informatique et Telecom")
ConceptCategory.create(label: "Commerce")
ConceptCategory.create(label: "Créativité, art et spectacles")
ConceptCategory.create(label: "Education, formation et emploi")
ConceptCategory.create(label: "Activités Financières, Assurance")
ConceptCategory.create(label: "Transport")
ConceptCategory.create(label: "Tourisme")
ConceptCategory.create(label: "Activités Immobilières")
ConceptCategory.create(label: "Mode et beauté")
ConceptCategory.create(label: "Santé et action sociale")
ConceptCategory.create(label: "Hôtel, café, restaurant")
ConceptCategory.create(label: "Economie sociale et solidaire")
ConceptCategory.create(label: "Industrie")
ConceptCategory.create(label: "Artisanat")
ConceptCategory.create(label: "Environnement")
ConceptCategory.create(label: "Agriculture, sylviculture, pêche")
ConceptCategory.create(label: "Réparation")
ConceptCategory.create(label: "Construction, Btp")
ConceptCategory.create(label: "Profession Libérale")
ConceptCategory.create(label: "Maison, Habitat")

# Skills
Skill.delete_all
Skill.create(label: "Analytics")
Skill.create(label: "Analytical")
Skill.create(label: "Applications")
Skill.create(label: "Application Development")
Skill.create(label: "Attention to Detail")
Skill.create(label: "Architecture")
Skill.create(label: "Big Data")
Skill.create(label: "Business Analytics")
Skill.create(label: "Business Intelligence")
Skill.create(label: "Business Process Modeling")
Skill.create(label: "Cloud Computing")
Skill.create(label: "Code")
Skill.create(label: "Coding")
Skill.create(label: "Computer")
Skill.create(label: "Communication")
Skill.create(label: "Content Strategy")
