# encoding: utf-8
ConceptCategory.delete_all
ConceptCategory.create(label: "Services")
ConceptCategory.create(label: "Informatique et Telecom")
ConceptCategory.create(label: "Commerce")
ConceptCategory.create(label: "Créativité, art et spectacles")
ConceptCategory.create(label: "Education, formation et emploi")
ConceptCategory.create(label: "Activités Financières, Assurance")
ConceptCategory.create(label: "Transport")
ConceptCategory.create(label: "Tourisme")
ConceptCategory.create(label: "Activités Immobilières")
ConceptCategory.create(label: "Mode et beauté")
ConceptCategory.create(label: "Santé et action sociale")
ConceptCategory.create(label: "Hôtel, café, restaurant")
ConceptCategory.create(label: "Economie sociale et solidaire")
ConceptCategory.create(label: "Industrie")
ConceptCategory.create(label: "Artisanat")
ConceptCategory.create(label: "Environnement")
ConceptCategory.create(label: "Agriculture, sylviculture, pêche")
ConceptCategory.create(label: "Réparation")
ConceptCategory.create(label: "Construction, Btp")
ConceptCategory.create(label: "Profession Libérale")
ConceptCategory.create(label: "Maison, Habitat")
