# encoding: utf-8

# Link Interaction Type
# InteractionType.delete_all
# InteractionType.create(name: 'ToRead')
# InteractionType.create(name: 'AlreadyRead')
# InteractionType.create(name: 'Useless')
# InteractionType.create(name: 'Priority')






# Concept categories
# ConceptCategory.delete_all
# ConceptCategory.create(label: 'Logiciels, Applications')
# ConceptCategory.create(label: 'Sharing Economy : Economie de partage')
# ConceptCategory.create(label: 'Outils BtoB, Services aux Entreprises')
# ConceptCategory.create(label: 'Logiciels, Applications')
# ConceptCategory.create(label: 'Maison, Habitat, Art de Vivre')
# ConceptCategory.create(label: 'Restauration, Gastronomie, Vin')
# ConceptCategory.create(label: 'Fintech : Banque, Assurance, Crowdfunding, Finance')
# ConceptCategory.create(label: 'Emploi, Recrutement, Formation')
# ConceptCategory.create(label: 'Santé, Sport, Bien-Etre')
# ConceptCategory.create(label: 'Communication, Marketing')
# ConceptCategory.create(label: 'Mode, Habillement, Accessoires')
# ConceptCategory.create(label: 'Smart City, Mobilité, Transport')
# ConceptCategory.create(label: 'Tourisme, Voyages, Hôtellerie')
# ConceptCategory.create(label: 'ArtTech, Entertainment : Créativité, arts et spectacles')
# ConceptCategory.create(label: 'Handicap, Charité, Solidarité – Economie Sociale et Solidaire')
# ConceptCategory.create(label: 'IoT – Objets Connectés, Hi Tech')
# ConceptCategory.create(label: 'Silver Economy, Services à la Personne')
# ConceptCategory.create(label: 'Big Data')
# ConceptCategory.create(label: 'GreenTech: Energie, Environnement')
# ConceptCategory.create(label: 'Jeux, Paris en Ligne ')
# ConceptCategory.create(label: 'Réparation')
# ConceptCategory.create(label: 'Biotech, Medtech')
# ConceptCategory.create(label: 'E-Gov, Open Data')
# ConceptCategory.create(label: 'Agriculture, sylviculture, pêche')


# Skills
# Skill.delete_all
# Skill.create(label: 'Analyse de comptes')
# Skill.create(label: 'Gestion de comptes')
# Skill.create(label: 'Comptabilité')
# Skill.create(label: 'Systèmes Logiciels Comptables')
# Skill.create(label: 'Principes de la Comptabilité')
# Skill.create(label: 'Process Comptables')
# Skill.create(label: 'Précision')
# Skill.create(label: 'Écoute Active')
# Skill.create(label: 'Détecter et empêcher une crise')
# Skill.create(label: "S'adapter à l'environnement")
# Skill.create(label: 'Secrétériat')
# Skill.create(label: 'Administratif')
# Skill.create(label: 'Adobe Illustrator')
# Skill.create(label: 'Adobe InDesign')
# Skill.create(label: 'Adobe Photoshop')
# Skill.create(label: 'ADP')
# Skill.create(label: 'Publicité')
# Skill.create(label: "Rapport d'obsolescence")
# Skill.create(label: 'Algorithmie')
# Skill.create(label: 'Analyser')
# Skill.create(label: 'Design de base de données')
# Skill.create(label: "Analyse d'émotions")
# Skill.create(label: 'Android')
# Skill.create(label: 'Etablissement de rapports annuels')
# Skill.create(label: 'Anticiper les objections')
# Skill.create(label: 'APIs')
# Skill.create(label: 'Architecture')
# Skill.create(label: 'Art Design')
# Skill.create(label: 'Artiste')
# Skill.create(label: 'Asset Management')
# Skill.create(label: 'Attentif(ve) au détail')
# Skill.create(label: 'Audit')
# Skill.create(label: "Gestion d'Autorité")
# Skill.create(label: 'AutoCAD')
# Skill.create(label: 'Gestion des plans de secours')
# Skill.create(label: 'Gestion des dépôts bancaires')
# Skill.create(label: 'Gestion des régulations bancaires')
# Skill.create(label: 'Banque et Financement')
# Skill.create(label: 'Big Data')
# Skill.create(label: 'Paiement de factures')
# Skill.create(label: 'Blogging')
# Skill.create(label: 'Brainstorming')
# Skill.create(label: 'Gestion de marques')
# Skill.create(label: 'Marketing de marques')
# Skill.create(label: 'Etablir un budget')
# Skill.create(label: 'Construire des partenariats')
# Skill.create(label: 'Business Analyst')
# Skill.create(label: 'Business Design')
# Skill.create(label: 'Business Development')
# Skill.create(label: 'Business Intelligence')
# Skill.create(label: 'Business Manager')
# Skill.create(label: 'Dessiner des process business')
# Skill.create(label: 'Business Storytelling')
# Skill.create(label: 'C')
# Skill.create(label: 'C++')
# Skill.create(label: 'Gestion de call center')
# Skill.create(label: 'Gestion de cash')
# Skill.create(label: 'Calcul Mental')
# Skill.create(label: 'Gestion des certifications')
# Skill.create(label: 'Analyse financière')
# Skill.create(label: 'Contrôle Financier')
# Skill.create(label: 'Expert en Sinistres')
# Skill.create(label: 'Clarté')
# Skill.create(label: 'Relation Clients')
# Skill.create(label: 'Service Clients')
# Skill.create(label: 'Support Client')
# Skill.create(label: 'Ventes')
# Skill.create(label: 'Cloud Computing')
# Skill.create(label: 'Coaching')
# Skill.create(label: 'Communication')
# Skill.create(label: 'Analyse des concurrents')
# Skill.create(label: 'Statisticien')
# Skill.create(label: 'Gestion de la conformité')
# Skill.create(label: 'Concision')
# Skill.create(label: 'Recherche Opérationelle')
# Skill.create(label: 'Confiance')
# Skill.create(label: 'Configuration Infrastructure IT')
# Skill.create(label: 'Gestion des conflits')
# Skill.create(label: 'Résolution de conflit')
# Skill.create(label: 'Veille Technologique')
# Skill.create(label: 'Consulting')
# Skill.create(label: 'Management de Contenu')
# Skill.create(label: 'Content Management Systems (CMS)')
# Skill.create(label: 'Content Marketing')
# Skill.create(label: 'Content Promotion')
# Skill.create(label: 'Content Strategy')
# Skill.create(label: 'Contrats')
# Skill.create(label: 'Persuasion')
# Skill.create(label: 'Coordination')
# Skill.create(label: 'Corel Draw')
# Skill.create(label: 'Corel Word Perfect')
# Skill.create(label: 'Comptabilité des coûts')
# Skill.create(label: 'Courage')
# Skill.create(label: 'Créativité')
# Skill.create(label: 'Gestion de crédit')
# Skill.create(label: 'Crédits')
# Skill.create(label: 'CSS')
# Skill.create(label: 'Orienté sur le client')
# Skill.create(label: 'Relations clients')
# Skill.create(label: 'Service clients')
# Skill.create(label: 'Support Client')
# Skill.create(label: 'Data')
# Skill.create(label: 'Data Analysis')
# Skill.create(label: 'Data Engineering')
# Skill.create(label: 'Data Intelligence')
# Skill.create(label: 'Data Mining')
# Skill.create(label: 'Stockage de données')
# Skill.create(label: "Stratégie de d'exploitation de données")
# Skill.create(label: 'Data Warehousing')
# Skill.create(label: 'Database')
# Skill.create(label: 'Administration de base de données')
# Skill.create(label: 'Design de base de données')
# Skill.create(label: 'Gestion de base de données')
# Skill.create(label: 'Debugging')
# Skill.create(label: 'Design')
# Skill.create(label: 'Digital')
# Skill.create(label: 'Digital Marketing')
# Skill.create(label: 'Diplomatie')
# Skill.create(label: 'Marketing Direct')
# Skill.create(label: 'Ecrire de la documentation')
# Skill.create(label: 'Conduite')
# Skill.create(label: 'Connaissances en économie')
# Skill.create(label: 'Edition')
# Skill.create(label: 'Composants Electroniques')
# Skill.create(label: 'Emailing')
# Skill.create(label: 'Ingénierie')
# Skill.create(label: "Vendre les aspects fonctionnels et techniques d'un produit")
# Skill.create(label: 'Enthousiaste')
# Skill.create(label: "Gestion d'évènements")
# Skill.create(label: 'Excel')
# Skill.create(label: 'Executive Assistant')
# Skill.create(label: 'Systèmes de Versionnement')
# Skill.create(label: 'Linux/Unix; Perl et Shell')
# Skill.create(label: "Capacité d'explication")
# Skill.create(label: 'Expression')
# Skill.create(label: 'Fabrication')
# Skill.create(label: 'Frameworks UI')
# Skill.create(label: 'Systèmes de fichiers')
# Skill.create(label: 'FileMaker Pro')
# Skill.create(label: 'Finance')
# Skill.create(label: 'Conseiller Financier')
# Skill.create(label: 'Analyse Financière')
# Skill.create(label: "Rapports d'activités financières")
# Skill.create(label: 'Logiciels de finance')
# Skill.create(label: 'Analyse de bilans Financiers')
# Skill.create(label: 'Bilans financiers')
# Skill.create(label: 'Immobilisations (Comptabilité)')
# Skill.create(label: 'Flexibilité')
# Skill.create(label: 'Suivre les spécifications techniques')
# Skill.create(label: 'Prévisions')
# Skill.create(label: 'Fortran')
# Skill.create(label: 'Levée de fonds')
# Skill.create(label: 'Développement Jeux Vidéo')
# Skill.create(label: 'Etablir des objectifs')
# Skill.create(label: 'Design Graphique')
# Skill.create(label: 'Gestion de croissance')
# Skill.create(label: 'Hadoop')
# Skill.create(label: 'Gestion des objections')
# Skill.create(label: 'SQL')
# Skill.create(label: 'Hardware')
# Skill.create(label: 'Système de santé')
# Skill.create(label: 'Help Desk')
# Skill.create(label: 'Recrutement')
# Skill.create(label: 'Hospitalité')
# Skill.create(label: 'Gestion de structures hôtelières')
# Skill.create(label: 'HTML')
# Skill.create(label: 'Ressources Humaines')
# Skill.create(label: 'Identifer les conflits')
# Skill.create(label: 'Imagination')
# Skill.create(label: 'Innovation')
# Skill.create(label: 'Assurance')
# Skill.create(label: 'Technologies Intégrées')
# Skill.create(label: "Calcul d'intérêts")
# Skill.create(label: 'Marketing International')
# Skill.create(label: 'Relations Interpersonnelles')
# Skill.create(label: 'Faire passer des entretiens')
# Skill.create(label: 'Etablissement de factures')
# Skill.create(label: 'iOS')
# Skill.create(label: 'Python')
# Skill.create(label: 'iPhone')
# Skill.create(label: 'IT Manager')
# Skill.create(label: 'Optimisation Informatique')
# Skill.create(label: 'Sécurité Informatique')
# Skill.create(label: 'PHP')
# Skill.create(label: 'Java')
# Skill.create(label: 'Ruby')
# Skill.create(label: 'Javascript')
# Skill.create(label: 'Rapports sur les coûts salariaux')
# Skill.create(label: 'Journalisme')
# Skill.create(label: 'Langages')
# Skill.create(label: 'Légal')
# Skill.create(label: 'LinkedIn')
# Skill.create(label: 'Linux')
# Skill.create(label: 'Ecoute Active')
# Skill.create(label: 'Mac')
# Skill.create(label: 'Gestion de projets avec deadline')
# Skill.create(label: 'Gestion de projets')
# Skill.create(label: 'Management')
# Skill.create(label: 'Analyse de marché')
# Skill.create(label: 'Stratégie de marché')
# Skill.create(label: 'Marketing')
# Skill.create(label: 'Automatisation du Marketing')
# Skill.create(label: 'Mathématiques')
# Skill.create(label: 'Matlab')
# Skill.create(label: 'Maya')
# Skill.create(label: 'Mécanique')
# Skill.create(label: 'Gestion médias')
# Skill.create(label: 'Etablir des métriques')
# Skill.create(label: 'Microsoft ASP.NET MVC, Web API Experience')
# Skill.create(label: 'Microsoft Excel')
# Skill.create(label: 'Microsoft Office')
# Skill.create(label: 'Microsoft Outlook')
# Skill.create(label: 'Microsoft Publisher')
# Skill.create(label: 'Microsoft Visual')
# Skill.create(label: 'Microsoft Word')
# Skill.create(label: 'Applications Mobile ')
# Skill.create(label: 'Developpement Mobile ')
# Skill.create(label: 'Marketing Mobile')
# Skill.create(label: 'Modélisation')
# Skill.create(label: 'Source de motivation')
# Skill.create(label: 'Motivé(e)')
# Skill.create(label: 'Multiplatformes')
# Skill.create(label: 'Multitâche')
# Skill.create(label: 'MySQL')
# Skill.create(label: 'Analyse du besoin')
# Skill.create(label: 'Négociation')
# Skill.create(label: 'Architecture des réseaux')
# Skill.create(label: 'Opérations des réseaux')
# Skill.create(label: 'Sécurité des réseaux')
# Skill.create(label: 'Networking')
# Skill.create(label: 'Réseaux')
# Skill.create(label: 'Newsletters')
# Skill.create(label: 'Marketing de niche')
# Skill.create(label: 'Node.js')
# Skill.create(label: 'Assistant(e) de bureau')
# Skill.create(label: 'Gestion de bureaux')
# Skill.create(label: 'e-Marketing')
# Skill.create(label: "Ouverture d'esprit")
# Skill.create(label: 'Optimiste')
# Skill.create(label: 'Oracle')
# Skill.create(label: 'Gestion des commandes')
# Skill.create(label: 'Organisation')
# Skill.create(label: 'Ventes internationales')
# Skill.create(label: 'Paralegal')
# Skill.create(label: 'Code reviews et design reviews')
# Skill.create(label: 'Passion')
# Skill.create(label: 'Fiches de paie')
# Skill.create(label: 'Paiement de salaires')
# Skill.create(label: 'Problèmes sur salaires')
# Skill.create(label: 'Impôts sur salaires')
# Skill.create(label: 'Perl')
# Skill.create(label: 'Persévérance')
# Skill.create(label: 'Assistant Personnel')
# Skill.create(label: 'Impôts personnels')
# Skill.create(label: 'Persuasion')
# Skill.create(label: 'Photo')
# Skill.create(label: 'PHP')
# Skill.create(label: 'Planification')
# Skill.create(label: 'Scrum')
# Skill.create(label: 'Estimation de prix')
# Skill.create(label: 'Etablir des process')
# Skill.create(label: 'Démonstration de produits')
# Skill.create(label: 'Développement Produit')
# Skill.create(label: 'Product Management')
# Skill.create(label: 'Product Manager')
# Skill.create(label: 'Promotion Produit')
# Skill.create(label: 'Recherche Produit')
# Skill.create(label: 'Support Produit')
# Skill.create(label: 'Formation aux produits')
# Skill.create(label: 'Pertes et Profits')
# Skill.create(label: 'Programmation')
# Skill.create(label: 'Coordination de projets')
# Skill.create(label: 'Gestion de projet')
# Skill.create(label: 'Promotion')
# Skill.create(label: 'Relations public')
# Skill.create(label: 'Prise de parole en public')
# Skill.create(label: 'Python')
# Skill.create(label: 'Assurance Qualité')
# Skill.create(label: 'Immobilier')
# Skill.create(label: 'Réceptivité')
# Skill.create(label: 'Réconciliation')
# Skill.create(label: 'Recrutement')
# Skill.create(label: 'Construction de relations')
# Skill.create(label: 'Gestion des relations')
# Skill.create(label: 'Outils de reporting')
# Skill.create(label: 'Production de rapports graphiques')
# Skill.create(label: 'Recherche')
# Skill.create(label: 'Restauration')
# Skill.create(label: 'Vente au détail')
# Skill.create(label: 'Prévision de revenus')
# Skill.create(label: 'Gestion des risques')
# Skill.create(label: 'Preneur(se) de risques')
# Skill.create(label: 'Ruby')
# Skill.create(label: 'Ruby on Rails')
# Skill.create(label: 'Ventes')
# Skill.create(label: 'Associé en ventes')
# Skill.create(label: 'Presentation des ventes')
# Skill.create(label: 'Gestion des reçus')
# Skill.create(label: 'Support des ventes')
# Skill.create(label: 'Sales Tracking')
# Skill.create(label: 'SAP Business Solutions Toolset')
# Skill.create(label: 'SEO')
# Skill.create(label: 'Securité')
# Skill.create(label: 'Seveurs')
# Skill.create(label: 'Social Media Management')
# Skill.create(label: 'Social Media Marketing')
# Skill.create(label: 'Social Networking')
# Skill.create(label: 'Développement Logiciel')
# Skill.create(label: 'Software Engineering')
# Skill.create(label: 'Gestion de logiciels')
# Skill.create(label: 'Gestion de qualité logicielle')
# Skill.create(label: 'Représentant en ventes de logiciels')
# Skill.create(label: 'Java')
# Skill.create(label: 'Solution Oriented')
# Skill.create(label: 'Inventaire')
# Skill.create(label: 'Prise de parole')
# Skill.create(label: 'Ecriture de discours')
# Skill.create(label: 'Feuilles de calcul (Excel)')
# Skill.create(label: 'SQL')
# Skill.create(label: 'Endurance')
# Skill.create(label: 'Analyse statistique')
# Skill.create(label: 'Stockage')
# Skill.create(label: 'Storytelling')
# Skill.create(label: 'Plannification Stratégique')
# Skill.create(label: 'Stratégie')
# Skill.create(label: 'Résolution de problèmes')
# Skill.create(label: 'Forte éthique de travail')
# Skill.create(label: 'Diagrammes de SWOT')
# Skill.create(label: 'Esprit de Synthèse')
# Skill.create(label: 'Administration Système')
# Skill.create(label: 'Logiciels Système')
# Skill.create(label: 'Analyse des impôts')
# Skill.create(label: 'Verification des impôts applicables')
# Skill.create(label: "Remplir fiches d'imposition")
# Skill.create(label: "Lois sur l'imposition")
# Skill.create(label: "Bilan d'imposition")
# Skill.create(label: 'Etablir Déclaration de revenus')
# Skill.create(label: 'Logiciels de taxes')
# Skill.create(label: 'Enseignement')
# Skill.create(label: 'Team Building')
# Skill.create(label: 'Team Oriented')
# Skill.create(label: 'Travail en équipe')
# Skill.create(label: 'Support Technique')
# Skill.create(label: 'Test de stratégie Marketing')
# Skill.create(label: 'Tester')
# Skill.create(label: 'Think Outside the Box')
# Skill.create(label: 'Gestion du temps')
# Skill.create(label: 'Formation')
# Skill.create(label: 'Coordinateur de Formations')
# Skill.create(label: 'Transformation')
# Skill.create(label: 'Expression du besoin en spécifications détaillées')
# Skill.create(label: 'Debug de niveau 1')
# Skill.create(label: 'UI / UX')
# Skill.create(label: 'Unix')
# Skill.create(label: 'Ergonomie')
# Skill.create(label: 'Test utilisateurs')
# Skill.create(label: 'Gestion relation fournisseurs')
# Skill.create(label: 'Communication Verbale')
# Skill.create(label: 'Virtualization')
# Skill.create(label: 'VIsio')
# Skill.create(label: 'Vision')
# Skill.create(label: 'Visualisation')
# Skill.create(label: 'Gestion des avoirs')
# Skill.create(label: 'Gestion de contenu web')
# Skill.create(label: 'Design web')
# Skill.create(label: 'Programmation Web')
# Skill.create(label: 'Remse en question')
# Skill.create(label: 'Windows')
# Skill.create(label: 'WordPress')
# Skill.create(label: 'Indépendant')
# Skill.create(label: 'Scrum')
# Skill.create(label: 'C#')
# Skill.create(label: 'Spécifications Techniques Détaillées')
# Skill.create(label: 'Ecriture')
# Skill.create(label: 'Communication Ecrite')
# Skill.create(label: 'XHTML')
# Skill.create(label: 'XML')
# Skill.create(label: "Rapports d'activité annuelle")


# CharacterTraits
# CharacterTrait.delete_all
# CharacterTrait.create(label: 'Accueillant(e)')
# CharacterTrait.create(label: 'Adroit(e)')
# CharacterTrait.create(label: 'Accessible')
# CharacterTrait.create(label: 'Agréable')
# CharacterTrait.create(label: 'Aidant(e)')
# CharacterTrait.create(label: 'Aimable')
# CharacterTrait.create(label: 'Altruiste')
# CharacterTrait.create(label: 'Ambitieux(euse)')
# CharacterTrait.create(label: 'Amusant(e)')
# CharacterTrait.create(label: 'Apaisant(e)')
# CharacterTrait.create(label: 'Accessible')
# CharacterTrait.create(label: 'Appliqué(e)')
# CharacterTrait.create(label: 'Assertif(ive)')
# CharacterTrait.create(label: 'Astucieux(euse)')
# CharacterTrait.create(label: 'Attachant')
# CharacterTrait.create(label: 'Attentif(ive)')
# CharacterTrait.create(label: 'Attentionné(e)')
# CharacterTrait.create(label: 'Audacieux(euse)')
# CharacterTrait.create(label: 'Autonome')
# CharacterTrait.create(label: 'Avenant(e)')
# CharacterTrait.create(label: 'Aventureux(euse)')
# CharacterTrait.create(label: 'Bienveillant(e)')
# CharacterTrait.create(label: 'Calme')
# CharacterTrait.create(label: 'Captivant(e)')
# CharacterTrait.create(label: 'Chaleureux')
# CharacterTrait.create(label: 'Charismatique')
# CharacterTrait.create(label: 'Charmant(e)')
# CharacterTrait.create(label: 'Combatif(ive)')
# CharacterTrait.create(label: 'Communicatif(ive)')
# CharacterTrait.create(label: 'Compréhensif(ive)')
# CharacterTrait.create(label: 'Concentré (capacité à être)')
# CharacterTrait.create(label: 'Conciliant(e)')
# CharacterTrait.create(label: 'Confiant(e)')
# CharacterTrait.create(label: 'Conformiste')
# CharacterTrait.create(label: 'Consciencieux')
# CharacterTrait.create(label: 'Convaincant(e)')
# CharacterTrait.create(label: 'Coopératif(ive)')
# CharacterTrait.create(label: 'Courageux(euse)')
# CharacterTrait.create(label: 'Courtois(e)')
# CharacterTrait.create(label: 'Créatif(ive)')
# CharacterTrait.create(label: 'Cultivé(e)')
# CharacterTrait.create(label: 'Curieux(euse)')
# CharacterTrait.create(label: 'Débrouillard(e)')
# CharacterTrait.create(label: 'Décidé(e)')
# CharacterTrait.create(label: 'Délicat(e)')
# CharacterTrait.create(label: 'Déterminé(e)')
# CharacterTrait.create(label: 'Dévoué(e)')
# CharacterTrait.create(label: 'Digne de confiance')
# CharacterTrait.create(label: 'Discipliné(e)')
# CharacterTrait.create(label: 'Diplomate')
# CharacterTrait.create(label: 'Direct(e)')
# CharacterTrait.create(label: 'Discipliné(e)')
# CharacterTrait.create(label: 'Discret(e)')
# CharacterTrait.create(label: 'Disert(e)')
# CharacterTrait.create(label: 'Disponible')
# CharacterTrait.create(label: 'Doux(ouce)')
# CharacterTrait.create(label: 'Droit(e)')
# CharacterTrait.create(label: 'Drôle')
# CharacterTrait.create(label: 'Dynamique')
# CharacterTrait.create(label: 'Ecoute (à l’)')
# CharacterTrait.create(label: 'Efficace')
# CharacterTrait.create(label: 'Eloquent(e)')
# CharacterTrait.create(label: 'Empathique')
# CharacterTrait.create(label: 'Encourageant(e)')
# CharacterTrait.create(label: 'Endurant(e)')
# CharacterTrait.create(label: 'Energique')
# CharacterTrait.create(label: 'Engagé')
# CharacterTrait.create(label: 'Enthousiaste')
# CharacterTrait.create(label: 'Entreprenant')
# CharacterTrait.create(label: 'Epanoui(e)')
# CharacterTrait.create(label: 'Equitable')
# CharacterTrait.create(label: 'Esprit d’équipe')
# CharacterTrait.create(label: 'Exemplaire')
# CharacterTrait.create(label: 'Extraverti(e)')
# CharacterTrait.create(label: 'Ferme')
# CharacterTrait.create(label: 'Fidèle')
# CharacterTrait.create(label: 'Fin(e)')
# CharacterTrait.create(label: 'Flexible')
# CharacterTrait.create(label: 'Fort(e)')
# CharacterTrait.create(label: 'Franc(he)')
# CharacterTrait.create(label: 'Gai(e)')
# CharacterTrait.create(label: 'Généreux(euse)')
# CharacterTrait.create(label: 'Gentil(le)')
# CharacterTrait.create(label: 'Habile')
# CharacterTrait.create(label: 'Hardi(e)')
# CharacterTrait.create(label: 'Honnête')
# CharacterTrait.create(label: 'Humain(e)')
# CharacterTrait.create(label: 'Humble')
# CharacterTrait.create(label: 'Imaginatif(ive)')
# CharacterTrait.create(label: 'Impliqué(e)')
# CharacterTrait.create(label: 'Impulsif(ive)')
# CharacterTrait.create(label: 'Indépendant(e)')
# CharacterTrait.create(label: 'Indulgent(e)')
# CharacterTrait.create(label: 'Infatigable')
# CharacterTrait.create(label: 'Influent(e)')
# CharacterTrait.create(label: 'Ingénieux(euse)')
# CharacterTrait.create(label: 'Innovateur(trice)')
# CharacterTrait.create(label: 'Inspiré(e)')
# CharacterTrait.create(label: 'Intelligent(e)')
# CharacterTrait.create(label: 'Intègre')
# CharacterTrait.create(label: 'Intuitif(ive)')
# CharacterTrait.create(label: 'Inventif(ive)')
# CharacterTrait.create(label: 'Joueur(euse)')
# CharacterTrait.create(label: 'Jovial(e)')
# CharacterTrait.create(label: 'Juste')
# CharacterTrait.create(label: 'Leader')
# CharacterTrait.create(label: 'Logique')
# CharacterTrait.create(label: 'Loyal(e)')
# CharacterTrait.create(label: 'Lucide')
# CharacterTrait.create(label: 'Maître de soi')
# CharacterTrait.create(label: 'Malin(igne)')
# CharacterTrait.create(label: 'Marrant(e)')
# CharacterTrait.create(label: 'Méthodique')
# CharacterTrait.create(label: 'Mignon(ne)')
# CharacterTrait.create(label: 'Minutieux(euse)')
# CharacterTrait.create(label: 'Modeste')
# CharacterTrait.create(label: 'Motivé(e)')
# CharacterTrait.create(label: 'Naturel(le)')
# CharacterTrait.create(label: 'Novateur(trice)')
# CharacterTrait.create(label: 'Nuancé(e)')
# CharacterTrait.create(label: 'Objectif(ive)')
# CharacterTrait.create(label: 'Observateur(trice)')
# CharacterTrait.create(label: 'Obstiné(e)')
# CharacterTrait.create(label: 'Opiniâtre')
# CharacterTrait.create(label: 'Optimiste')
# CharacterTrait.create(label: 'Ordonné(e)')
# CharacterTrait.create(label: 'Organisateur(trice)')
# CharacterTrait.create(label: 'Organisé(e)')
# CharacterTrait.create(label: 'Original(e)')
# CharacterTrait.create(label: 'Ouvert(e) d’esprit')
# CharacterTrait.create(label: 'Pacificateur(trice)')
# CharacterTrait.create(label: 'Paisible')
# CharacterTrait.create(label: 'Passionnant(e)')
# CharacterTrait.create(label: 'Patient(e)')
# CharacterTrait.create(label: 'Persévérant(e)')
# CharacterTrait.create(label: 'Persuasif(ive)')
# CharacterTrait.create(label: 'Pétillante(e)')
# CharacterTrait.create(label: 'Philosophe')
# CharacterTrait.create(label: 'Planificateur(trice)')
# CharacterTrait.create(label: 'Poli(e)')
# CharacterTrait.create(label: 'Polyvalent(e)')
# CharacterTrait.create(label: 'Ponctuel(le)')
# CharacterTrait.create(label: 'Pondéré(e)')
# CharacterTrait.create(label: 'Posé(e)')
# CharacterTrait.create(label: 'Positif(ive)')
# CharacterTrait.create(label: 'Pragmatique')
# CharacterTrait.create(label: 'Pratique')
# CharacterTrait.create(label: 'Précis(e)')
# CharacterTrait.create(label: 'Prévenant(e)')
# CharacterTrait.create(label: 'Prévoyant(e)')
# CharacterTrait.create(label: 'Productif(ive)')
# CharacterTrait.create(label: 'Protecteur(trice)')
# CharacterTrait.create(label: 'Prudent(e)')
# CharacterTrait.create(label: 'Pugnace')
# CharacterTrait.create(label: 'Quièt(e)')
# CharacterTrait.create(label: 'Raisonnable')
# CharacterTrait.create(label: 'Rassurant(e)')
# CharacterTrait.create(label: 'Rationnel(le)')
# CharacterTrait.create(label: 'Réaliste')
# CharacterTrait.create(label: 'Réconfortant(e)')
# CharacterTrait.create(label: 'Réfléchi(e)')
# CharacterTrait.create(label: 'Réservé(e)')
# CharacterTrait.create(label: 'Résistant(e)')
# CharacterTrait.create(label: 'Résolu(e)')
# CharacterTrait.create(label: 'Respectueux(euse)')
# CharacterTrait.create(label: 'Responsable')
# CharacterTrait.create(label: 'Rigolo(te)')
# CharacterTrait.create(label: 'Rigoureux(euse)')
# CharacterTrait.create(label: 'Rusé(e)')
# CharacterTrait.create(label: 'Sage')
# CharacterTrait.create(label: 'Séduisant(e)')
# CharacterTrait.create(label: 'Sensible')
# CharacterTrait.create(label: 'Serein(e)')
# CharacterTrait.create(label: 'Sérieux(euse)')
# CharacterTrait.create(label: 'Serviable')
# CharacterTrait.create(label: 'Sincère')
# CharacterTrait.create(label: 'Sociable')
# CharacterTrait.create(label: 'Social(e)')
# CharacterTrait.create(label: 'Soigneux(euse)')
# CharacterTrait.create(label: 'Solide')
# CharacterTrait.create(label: 'Souple')
# CharacterTrait.create(label: 'Souriant(e)')
# CharacterTrait.create(label: 'Spontané(e)')
# CharacterTrait.create(label: 'Sportif(ive)')
# CharacterTrait.create(label: 'Stable')
# CharacterTrait.create(label: 'Stratège')
# CharacterTrait.create(label: 'Studieux(euse)')
# CharacterTrait.create(label: 'Sûr(e)desoi')
# CharacterTrait.create(label: 'Sympa(thique!)')
# CharacterTrait.create(label: 'Talentueux(euse)')
# CharacterTrait.create(label: 'Tempéré(e)')
# CharacterTrait.create(label: 'Tenace')
# CharacterTrait.create(label: 'Tendre')
# CharacterTrait.create(label: 'Tolérant(e)')
# CharacterTrait.create(label: 'Timide')
# CharacterTrait.create(label: 'Tranquille')
# CharacterTrait.create(label: 'Travailleur(euse)')
# CharacterTrait.create(label: 'Vaillant(e)')
# CharacterTrait.create(label: 'Valeureux(euse)')
# CharacterTrait.create(label: 'Vif(ive)')
# CharacterTrait.create(label: 'Vigilant(e)')
# CharacterTrait.create(label: 'Volontaire')
# CharacterTrait.create(label: 'Vrai(e)')
# CharacterTrait.create(label: 'Zen')



# # UsefulLinks Categories
# UsefulLinkCategory.delete_all
# UsefulLinkCategory.create(label: 'Law')
# UsefulLinkCategory.create(label: 'Money')
# UsefulLinkCategory.create(label: 'Info')
# UsefulLinkCategory.create(label: 'Mentorship')
# UsefulLinkCategory.create(label: 'Associates')
# UsefulLinkCategory.create(label: 'Housing')
# UsefulLinkCategory.create(label: 'BusinessIdea')
# UsefulLinkCategory.create(label: 'Technical')
#
#
# # UserLinks Types
# UserLinkType.delete_all
# UserLinkType.create(title: 'Mentor')
# UserLinkType.create(title: 'Partner')



